---
title: "p8105 Homework 6"
output: github_document
author: Tory Lynch
date: November 26, 2018
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(mgcv)
library(MASS)
```

#### Problem 1
```{r data, message = FALSE, warning = FALSE}
#Load and clean data 
homicide_data = read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "), 
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved", 
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>% 
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) %>% 
  mutate(
    race = as.factor(case_when(
      victim_race == "White" ~ "white", 
      victim_race != "White" ~ "non-white"
    ))
  ) %>% 
  mutate(age = as.numeric(victim_age)) %>% 
  mutate(race = fct_relevel(race, "white")) %>% 
  mutate(sex = fct_relevel(victim_sex, "Female")) %>% 
  mutate(resolution = fct_relevel(resolution, "unsolved"))
```

##### Logistic model for Baltimore, MD
```{r}
logistic_model = homicide_data %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(resolution ~ age + sex + race, data = ., family = binomial())

logistic_model %>% 
  broom::tidy(., conf.int = TRUE) %>% 
  mutate(
    OR = exp(estimate), 
    ci.high = exp(conf.high),
    ci.low = exp(conf.low)
  ) %>% 
  dplyr::select(term, OR, ci.high, ci.low) %>% 
 knitr:: kable(digits = 4)
```

##### Logistic model for all cities 
```{r}
 homicide_data %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(model = map(data, ~glm(resolution ~ race + age + sex, data = ., family = binomial())),
         model = map(model, broom::tidy, conf.int = TRUE)) %>% 
  dplyr::select(-data) %>%    
  unnest() %>% 
  mutate(
    OR = exp(estimate), 
    ci.high = exp(conf.high),
    ci.low = exp(conf.low)
  ) %>% 
  filter(term == "racenon-white") %>% 
  dplyr::select(city_state, term, OR, ci.high, ci.low) %>% 
 knitr:: kable(digits = 4)
```
```{r}
 nested_homicide_data = homicide_data %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(model = map(data, ~glm(resolution ~ race, data = ., family = binomial())),
         model = map(model, broom::tidy, conf.int = TRUE)) %>% 
  dplyr::select(-data) %>%    
  unnest() %>% 
  mutate(
    OR = exp(estimate), 
    ci.high = exp(conf.high),
    ci.low = exp(conf.low)
  ) %>% 
  filter(term == "racenon-white") %>% 
  dplyr::select(city_state, term, OR, ci.high, ci.low) 

nested_homicide_data %>% 
  knitr::kable(digitis = 3)
```
 
```{r}
nested_homicide_data %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = ci.low, ymax = ci.high)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(
    title = "Odds of solving homicides of non-white victims compared to white victims
    in 47 American cities between 2007 - 2015",
    x = "City", 
    y = "Adjusted OR", 
    caption = "data source: Washington Post"
  )
```
 
